apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jade-shooter
  namespace: {{ .Release.Namespace }}
spec:
  ingressClassName: traefik
  rules:
    - host: jade-shooter.rancher.localhost
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: jade-shooter
                port:
                  number: 80
