apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jade-shooter
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/jwsy/simplest-k8s.git
    targetRevision: helm4
    path: .
    helm:
      valueFiles:
        - values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: jade-shooter

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
