apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitea
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://dl.gitea.com/charts/
    chart: gitea
    targetRevision: 12.3.0
    helm:
      releaseName: gitea
      valueFiles:
        - values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: gitea

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
